apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  annotations:
    architecture: x86_64
    authoritative-source-url: registry.access.redhat.com
    build-date: 2019-10-29T16:44:53.794580
    commit.image.appsody.dev/author: Denilson Nastacio <dnastaci@us.ibm.com>
    commit.image.appsody.dev/committer: Denilson Nastacio <dnastaci@us.ibm.com>
    commit.image.appsody.dev/date: Wed Apr 1 21:06:45 2020 -0400
    commit.image.appsody.dev/message: Formatting
    commit.stack.appsody.dev/author: Steve Groeger <groeges@uk.ibm.com>
    commit.stack.appsody.dev/committer: GitHub <noreply@github.com>
    commit.stack.appsody.dev/contextDir: /incubator/java-openliberty
    commit.stack.appsody.dev/date: Tue Mar 10 21:35:36 2020 +0000
    commit.stack.appsody.dev/message: 'Merge pull request #313 from groeges/release-0.6'
    description: This image is the Kabanero development container for the java-openliberty
      stack
    distribution-scope: public
    image.opencontainers.org/created: "2020-04-02T08:08:01-04:00"
    image.opencontainers.org/documentation: https://github.com/IBM/icpa-jee-tutorial
    image.opencontainers.org/revision: d29982f06de608980d7a7c31e5ba6f8553138444-modified
    image.opencontainers.org/source: https://github.com/IBM/icpa-jee-tutorial/tree/java-openliberty
    image.opencontainers.org/url: https://github.com/IBM/icpa-jee-tutorial
    k8s.io/description: The Universal Base Image is designed and engineered to be
      the base layer for all of your containerized applications, middleware and utilities.
      This base image is freely redistributable, but Red Hat only supports Red Hat
      technologies through subscriptions for Red Hat products. This image is maintained
      by Red Hat and updated regularly.
    k8s.io/display-name: Red Hat Universal Base Image 8
    maintainer: Red Hat, Inc.
    name: kabanero/java-openliberty
    openshift.io/expose-services: ""
    openshift.io/tags: base rhel8
    redhat.com/build-host: cpt-1002.osbs.prod.upshift.rdu2.redhat.com
    redhat.com/component: ubi8-container
    redhat.com/license_terms: https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI
    release: "277"
    stack.appsody.dev/authors: Mike Andrasak <andrasak@us.ibm.com>, Andy Mauer <ajmauer@us.ibm.com>,
      Scott Kurz <skurz@us.ibm.com>, Adam Wisniewski <awisniew@us.ibm.com>
    stack.appsody.dev/configured: docker.io/kabanero/java-openliberty:0.2
    stack.appsody.dev/created: "2020-03-10T21:42:07Z"
    stack.appsody.dev/description: Open Liberty & OpenJ9 using Maven
    stack.appsody.dev/documentation: https://github.com/kabanero-io/collections/tree/master/incubator/java-openliberty/README.md
    stack.appsody.dev/licenses: Apache-2.0
    stack.appsody.dev/revision: 5f7634c970b880bef90eeea4288153249e172d61
    stack.appsody.dev/source: https://github.com/kabanero-io/collections/tree/master/incubator/java-openliberty/image
    stack.appsody.dev/tag: docker.io/kabanero/java-openliberty:0.2.3
    stack.appsody.dev/title: Open Liberty
    stack.appsody.dev/url: https://github.com/kabanero-io/collections/tree/master/incubator/java-openliberty
    summary: Image for Kabanero java-openliberty development
    url: https://access.redhat.com/containers/#/registry.access.redhat.com/ubi8/images/8.1-277
    vcs-ref: c42933bcdbf9f1c232e981a5e40de257c3534c8e
    vcs-type: git
    vendor: Kabanero
    version: 0.2.3
  creationTimestamp: null
  labels:
    image.opencontainers.org/title: jee-sample
    stack.appsody.dev/id: java-openliberty
    stack.appsody.dev/version: 0.2.3
  name: jee-sample
spec:
  applicationImage: us.icr.io/ns_dnastaci_kabanero/jee-sample:0.0.3
  createKnativeService: false
  env:
  - name: db_server
    valueFrom:
      secretKeyRef:
        key: host
        name: sample-jee-db-secret
  - name: db_port
    valueFrom:
      secretKeyRef:
        key: port
        name: sample-jee-db-secret
  - name: db_user
    valueFrom:
      secretKeyRef:
        key: username
        name: sample-jee-db-secret
  - name: db_password
    valueFrom:
      secretKeyRef:
        key: password
        name: sample-jee-db-secret
  - name: db_database
    valueFrom:
      secretKeyRef:
        key: db
        name: sample-jee-db-secret
  expose: true
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /health/live
      port: 9080
    initialDelaySeconds: 5
    periodSeconds: 2
  readinessProbe:
    failureThreshold: 12
    httpGet:
      path: /health/ready
      port: 9080
    initialDelaySeconds: 5
    periodSeconds: 2
    timeoutSeconds: 1
  service:
    annotations:
      prometheus.io/scrape: "true"
    port: 9080
    type: NodePort
  serviceAccountName: default
  stack: java-openliberty
  version: 1.0.0
