--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "DEPARTMENT" (
		"DEPTNO" CHAR(3) NOT NULL,
		"DEPTNAME" VARCHAR(36) NOT NULL,
		"MGRNO" CHAR(6),
		"ADMRDEPT" CHAR(3) NOT NULL,
		"LOCATION" CHAR(16)
	)
	DATA CAPTURE NONE;

ALTER TABLE "DEPARTMENT" ADD CONSTRAINT "PK_DEPARTMENT" PRIMARY KEY
	("DEPTNO");


INSERT INTO "DEPARTMENT" VALUES('A00','SPIFFY COMPUTER SERVICE DIV.','000010','A00',NULL);    
INSERT INTO "DEPARTMENT" VALUES('B01','PLANNING','000020','A00',NULL);
INSERT INTO "DEPARTMENT" VALUES('C01','INFORMATION CENTER','000030','A00',NULL);
INSERT INTO "DEPARTMENT" VALUES('D01','DEVELOPMENT CENTER',NULL,'A00',NULL);
INSERT INTO "DEPARTMENT" VALUES('D11','MANUFACTURING SYSTEMS','000060','D01',NULL);
INSERT INTO "DEPARTMENT" VALUES('D21','ADMINISTRATION SYSTEMS','000070','D01',NULL);
INSERT INTO "DEPARTMENT" VALUES('E01','SUPPORT SERVICES','000050','A00',NULL);
INSERT INTO "DEPARTMENT" VALUES('E11','OPERATIONS','000090','E01',NULL);
INSERT INTO "DEPARTMENT" VALUES('E21','SOFTWARE SUPPORT','000100','E01',NULL);
INSERT INTO "DEPARTMENT" VALUES('F22','BRANCH OFFICE F2',NULL,'E01',NULL);
INSERT INTO "DEPARTMENT" VALUES('G22','BRANCH OFFICE G2',NULL,'E01',NULL);
INSERT INTO "DEPARTMENT" VALUES('H22','BRANCH OFFICE H2',NULL,'E01',NULL);
INSERT INTO "DEPARTMENT" VALUES('I22','BRANCH OFFICE I2',NULL,'E01',NULL);
INSERT INTO "DEPARTMENT" VALUES('J22','BRANCH OFFICE J2',NULL,'E01',NULL);
